version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: devtree
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.hello().ok' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
